server:
  port: 8090

spring:
  cloud:
    gateway:
      # 'server.webflux' katmanı eklendi
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          
      # Yönlendirme kuralları (routes) doğrudan gateway altındadır
          routes:
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1
    
            - id: flight-search-route
              uri: lb://flight-search-service
              predicates:
                - Path=/api/flights/**
              filters:
                - StripPrefix=1
    
            - id: currency-exchange-route
              uri: lb://currency-exchange-service
              predicates:
                - Path=/api/exchange/**
              filters:
                - StripPrefix=1
            - id: authentication-service
              uri: lb://authentication-service
              predicates:
                - Path= api/auth/**
              filters:
                - StripPrefix=1
