server:
  port: 8090

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1
    
            - id: flight-search-route
              uri: lb://flight-search-service
              predicates:
                - Path=/api/flights/**
              filters:
                - StripPrefix=1
    
            - id: currency-exchange-route
              uri: lb://currency-exchange-service
              predicates:
                - Path=/api/exchange/**
              filters:
                - StripPrefix=1
                
            - id: authentication-service
              uri: lb://authentication-service
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1

              id: user-service-swagger
              uri: lb://user-service
              predicates:
                - Path=/api/users/v3/api-docs
              filters:
                - StripPrefix=2
                
            - id: auth-service-swagger
              uri: lb://authentication-service
              predicates:
                - Path=/api/auth/v3/api-docs
              filters:
                - StripPrefix=2
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: Authentication Service
        url: /api/auth/v3/api-docs
      - name: User Service
        url: /api/users/v3/api-docs
