jwt:
  secret: "BuCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokCokUzunVeGuvenliBirAnahtarOlmalidir"
  expiration-ms: 86400000 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
