server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: 1 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
      
exchange-rates:
  usd-to-arp: 41.50
  eur-to-arp: 44.00
